Version id 4592 stable [ci skip]

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,144 +1,142 @@
-# ITKR Build
 language: r
-sudo: false
+warnings_are_errors: yes
 cache: packages
-warnings_are_errors: true
-use_bioc: true
-bioc_required: true
+bioc_required: yes
 cran: http://cran.rstudio.com
 dist: xenial
-
+addons:
+  apt:
+    packages:
+      - libcurl4-openssl-dev
+      - libxml2-dev
+      - libfftw3-dev
+      - libgsl0-dev
+      - mesa-common-dev
+      - libglu1-mesa-dev
+      - devscripts
+      - libomp-dev
+      - libhdf5-serial-dev
+      - libhdf5-dev
 os:
   - linux
   - osx
-
+osx_image: xcode9.4
+services: xvfb
 r:
-  - oldrel  
+  - 3.4
+  - 3.5
+  - 3.6
   - release
   - devel
-
-services:
-  - xvfb
-
-matrix: 
+jobs:
   allow_failures:
     - r: devel
-
-latex: false
-compiler: clang
-osx_image: xcode9
-
 env:
   global:
-  - R_BUILD_ARGS=" --no-build-vignettes --no-manual"
-  - R_CHECK_ARGS=" --timings --as-cran --no-manual --install-args=--build"
-  - RGL_USE_NULL=TRUE
-  - WARNINGS_ARE_ERRORS=1 
-  - DISPLAY=:99.0
-
+    - R_BUILD_ARGS="--no-manual"
+    - R_CHECK_ARGS="--as-cran --install-args=--build"
+    - RGL_USE_NULL=TRUE
+    - WARNINGS_ARE_ERRORS=1
+    - PROJECT_NAME=neuroconductor-releases
+    - DISPLAY=:99.0
+    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
+    - _R_CHECK_FORCE_SUGGESTS_=false
+    - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
 before_install:
-  - ulimit -n 2048  
+  - if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi
+  - ulimit -n 2048
   - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
   - export PROJ_DIR=`basename $PWD`
-  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
+  - echo "travis_wait*\.log$" >> .Rbuildignore
   - fname=travis_helpers.sh
   - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}  
-  - codename=`linux_codename`;
-  - if [ "${codename}" = "trusty" ];
-    then
-      start_xvfb ;
-    fi  
-  - export rver=`r_version`;
-  - export gh_user=`get_gh_user` ; echo $gh_user ;
-  - cat DESCRIPTION  
+  - cat ${fname}; source ${fname}; rm ${fname}
+  - cat DESCRIPTION
+  - start_xvfb ;
+  - jags_install || true;
+  - if `need_v8`; then v8_install || true; fi
+  - dcmtk_install || true;
+  - gsl_install 2.1 || true ;
+  - export rver=`r_version`; echo $rver ;
   - export PACKAGE_NAME=`package_name`
-  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck  
-  # does all the clang exports  
+  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+  - remove_neuroc_packages
+  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
   - x=`export_clang_cxx`; eval ${x}
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      no_open_mp ; 
-    fi  
+  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
   - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
-  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
-  - clang_cxx  
-  # - hdf5_install ;
-  - export cmake_version="3.14"
+  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+  - clang_cxx
+  - export cmake_version="3.11"
   - cmake --version
   - x=`cmake_setup`; echo "${x}"; eval ${x};
-  - ls ~/ ;
   - cmake --version
-  - ./cleanup      
-  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
+  - export ants_user=neuroconductor-releases
+  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
+    == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type
+    = 'source', repo = 'http://cran.rstudio.com')" ; fi
+  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then
+    export R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
+    ${R_CHECK_ARGS}" ; fi
+  - if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ITKR"
+    ; install_missing_remote_deps_all ${ants_user}/ITKR ; gh_binary_install ${ants_user}/ITKR
+    ; fi
+  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then
+    echo "Installing Missing Deps ANTsRCore" ; install_missing_remote_deps_all ${ants_user}/ANTsRCore;
+    gh_binary_install_passive ${ants_user}/ANTsRCore ; fi
+  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
+    != "ANTsR" ]]; then echo "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all
+    ${ants_user}/ANTsR ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
+  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
+    ; fi
+  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then hdf5_install ; fi
+  - cat DESCRIPTION
+  - install_remotes_no_dep
+  - cat DESCRIPTION
+  - echo $PATH ;
   - install_deps_no_suggests
-
+  - setup_python 3.6 false ;
+  - install_python_requirements ;
+  - R CMD javareconf || true ;
+  - sudo R CMD javareconf || true ;
+  - travis_run_cache
 script:
   - x=`export_clang_cxx`; eval ${x}
   - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
   - rm -f travis_wait*.log
-  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)  
+  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
   - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
   - rm -f travis_wait*.log
-  - if [[ $CHECK_RET -ne 0 ]];
-    then
-      echo "R CMD check failed"; 
-      check_fail; 
-      dump_logs; 
-      check_warnings ;      
-      travis_terminate 1;
-    fi
-
-after_failure:
-  - dump_logs
-
-after_success:
-  - dump_logs
-  - ls
-  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
-  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
-      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
-      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
-    fi
-  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;      
-  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}
-
-
-notifications:
-  email:
-    recipients:
-    - muschellij2@gmail.com
-    - stnava@gmail.com
-    on_success: change
-    on_failure: always
-
-# so no overwrite of linux build
+  - if [[ $CHECK_RET -ne 0 ]]; then echo "R CMD check failed"; check_fail; dump_logs;
+    travis_terminate 1; fi
+  - check_warnings
+after_success: dump_logs
+after_failure: dump_logs
 before_deploy:
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      rm -f *.tar.gz;
-    fi
-
+  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
+    PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv
+    ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
+    ; fi
+  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head
+    -n 1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
+    ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
+    ; fi
+  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
 deploy:
-  - provider: releases
-    api_key:
-      secure: "r7FsUfP8EozlZBDTIHzAE5ENqyeuopoWxxpKoAxkhGkDwB6rLDkNhjmFk3SZxP/8Sx51CeO1oFDUC/G5QWpfYdSYRIkq0GoubhGTDdOk3S1F6z4ncsi6DO24MkxxZbAb4e7lyK1bBaVla/SKm0QQivzqNn5g+jNLAjek4Yc2hBCUdtbyYk++fuGKsBVSC/VeahE9I6SsHQAZMViOAVgR6Y80cxeIzsVk6yFljOmc/EQxCVG8M1Rq/VZYnkZfLB5E35bbCehcdwHWjPvsP1TfbBDFo4DsyHhmIe1L6k7AtuFOrBl9zK0rBAMJznwHsI0D4SsNAwdFYrqK/tSMB7pTxDR90KfkQpFjt2JxBdz5msFVZAQqcuvbbNlrbnf0m5wtX2DPB6wuPwdRxmCMrXyT5EZE4bbYmKhF4l3DDX0snncZvusSwrHD+r90kriwgZm7ogWSRFATOLRXtEVrWGyQYCjZoAFM9vB8lL+/8yQbB80e3gYexyYI+AFzgmiNTPc+6TYF8UUKMUiBsdN5iqbdYYrmuTexKDC0So23XuBO3vlRLQLhjmtFwY/FNywneOpEfwVZfxIMeleuF0T7z0XDgPpFQ4PmXtpXqKQiAxI18dplxfG8vsyACeLnVfslF8H2/bWdRgMukDUlLyKFBLVHUFoSyo8zPAcBM+7P+mS9SbQ="
-    file: ${PKG_FILE_NAME}
-    skip_cleanup: true
-    on:
-      tags: true
-      repo: muschellij2/ITKR
-      all_branches: true
-      condition: "${gh_user} = muschellij2"
-  - provider: releases
-    api_key:
-      secure: UL/OXal9+cvomf7iDtJnAoVY8YEmVa7MECjbBrfnmGeloQ6yRhYVUk5sRlbPNM4VczdtN6/k8hH8LpN/3IT8Wqh+YxIaN0kw/0J05dzj1OLcilRKxTFtQo7i1VYqdTqytXbbvaISaVLF+0UjGIwfFARr/m/GZsKXV54wXhTFirY=
-    file: ${PKG_FILE_NAME}
-    skip_cleanup: true
-    on:
-      tags: true
-      repo: ${gh_user}/${PROJ_DIR}
-      all_branches: true
-      condition: "${gh_user} = stnava"
+  provider: releases
+  skip_cleanup: yes
+  token: $GITHUB_TOKEN
+  file_glob: yes
+  overwrite: yes
+  file: ${PACKAGE_NAME}*.t*gz
+  'on':
+    tags: yes
+after_deploy:
+  - echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
+    else run_coverage=; fi;
+  - if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then echo 'covr::coveralls(type
+    = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R
+    ; rm neuroc_covr.R ; fi
+
+# neuroc.deps commit id:871f223
